### ISSUE TITLE
pass

### ISSUE THREAD

**Issue by kunfeyekun** [turnkeymobileapps/help-center#1]
Hello,
I try xenforo mobile version on my webpage. But i forgot my password.
my mail address: <redacted>
my web page: www.kunfeyekun.org

Please Help me,
Good work

**Comment by vbresults** [comment]
@kunfeyekun Your password has been emailed (:

**Comment by kunfeyekun** [comment]
https://www.turnkeymobileapps.com/libraries/smart-app-banner/img/org.kunfeyekun.app.png

why not working?

**Comment by vbresults** [comment]
@kunfeyekun In the future, please open a separate ticket -- each issue needs to be in it's own ticket so others can find and upvote the issue more easily.  I have made a separate one here: #2 

Thank you for reporting (:
