### ISSUE TITLE
disappearing message box

### ISSUE THREAD

**Issue by wonko123** [turnkeymobileapps/help-center#10]
After upgrading to 2.1.1 the message box is not available on the website
![screen shot 2016-12-21 at 18 54 16](https://cloud.githubusercontent.com/assets/6016376/21402456/7e4d6e10-c7b0-11e6-9250-b13a2c54e068.png)
![screen shot 2016-12-21 at 18 53 33] before upgrade
(https://cloud.githubusercontent.com/assets/6016376/21402471/8e717ce6-c7b0-11e6-916b-46d05a0e6250.png)
done a fresh install after the first upgrade produced the issue.

**Comment by vbresults** [comment]
Hello,

Does this occur in-app, out of app, or both?

**Comment by wonko123** [comment]
both

**Comment by wonko123** [comment]
Just followed the latest upgrade and the problem persists as soon as the app is live the message box disappears on the website but works fine on the app, and when the app is turned of the message box reappears on the website.

**Comment by vbresults** [comment]
Please enable the add-on for about 2 hours so we can diagnose the problem and fix it

**Comment by wonko123** [comment]
Turned app on

**Comment by vbresults** [comment]
![screen shot 2016-12-25 at 7 44 36 am](https://cloud.githubusercontent.com/assets/7179668/21469132/4aa9308a-ca76-11e6-86a2-30bccfe595ce.png)

**Comment by vbresults** [comment]
Update: I found something in the source code, will send you and update momentarily

**Comment by vbresults** [comment]
@wonko123 Please try to download the add-on and do the full upgrade again
