### ISSUE TITLE
XenForo  IOS APP Error

### ISSUE THREAD

**Issue by toni-r** [turnkeymobileapps/help-center#11]
A user has noticed this on his Ipad
But I have just downloaded the latest version of the forum app.
Unfortunately this version crashes after starting. Only the forum logo appears.

The previous version ran flawlessly.

IPad Air 2, software version 8.4 (will not update!)

Can you find the cause or correct the app

**Comment by vbresults** [comment]
Fixed in 2.1.2 to be released soon; note this is iOS 8's final update, as it is used in under 5% of devices.
