### ISSUE TITLE
Tranfer to Free Plan doesn't work?

### ISSUE THREAD

**Issue by aminsabet** [turnkeymobileapps/help-center#12]
I have 3 apps on the paid plan which I am trying to transfer to free plan.  When I click on the button to do that, check the box next to "I have confirmed my app is eligible, and wish to transfer to the Free Mobile Apps package", and then click on "Transfer Now", it takes me back to the first page and from what I can tell, nothing has changed.

**Comment by vbresults** [comment]
Fixed, and the apps have been transferred (:
