### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by ernestdefoe** [turnkeymobileapps/help-center#17]
I am not receiving push notifications on my iPhone 6S Plus with the latest version of iOS. It was working before the 2.0 update. I know there was some issues with the first version of 2 but in the latest e-mail sent it said the issue was fixed but I am still not getting the notifications from my site. Thank you for this awesome app which I love so much more since version 2.

**Comment by vbresults** [comment]
I tried a diagnostic alert, and got this:

![img_0303](https://cloud.githubusercontent.com/assets/7179668/21740798/7d300978-d4ff-11e6-936b-61aecf4ab032.jpg)

So as far as push device registration and delivery goes, in the conventional sense, it works; that said, there is one thing I can think about immediately that might cause this.

**Comment by ernestdefoe** [comment]
I'm not sure what's going on but I'm not getting any alerts on my phone or iPad.

**Comment by vbresults** [comment]
@ernestdefoe Did you just uninstall and install the app again, then log in?

**Comment by vbresults** [comment]
@ernestdefoe I see a new device registered; is it receiving alerts again?

**Comment by ernestdefoe** [comment]
I tried uninstalling and reinstalling the app and it didn't work. Still not receiving the push notifications. I'm not sure why it's not.

**Comment by vbresults** [comment]
Just sent a diagnostic alert; did you receive it?

**Comment by ernestdefoe** [comment]
I did. So why are no alerts coming from my site?

**Comment by vbresults** [comment]
With this information I'm close to the answer; do you happen to receive conversation push alerts from your site?  I've attempted to send one

**Comment by ernestdefoe** [comment]
I did receive the notification from the post. I think the main thing is I didn't receive a push notification from a couple of likes. I know I used to get them. I am using Luke's post ratings addon. If you happen to need AdminCP access or anything just let me know.

**Comment by ernestdefoe** [comment]
I meant the PM not post. Yes I got the alert from that.

**Comment by vbresults** [comment]
Ok, thanks for performing these diagnostics, the problem has been located and fixed -- please update the add-on and the me know whether or not the problem persists

**Comment by ernestdefoe** [comment]
The site isn't loading. Just so you know.

**Comment by vbresults** [comment]
Fixed.

**Comment by ernestdefoe** [comment]
Awesome just downloaded and now updating the addon. Glad you were able to identify and fix this issue. Thank you again for your hard work.
