### ISSUE TITLE
My app not show on app store.

### ISSUE THREAD

**Issue by tohaitrieu** [turnkeymobileapps/help-center#23]
Dear support

my app was approved on 10th Jan but it not show on app store.

**Comment by vbresults** [comment]
https://itunes.apple.com/vn/app/me-doc-sach/id1192959824?ls=1&mt=8

It is available in the Vietnam app store.  At the moment, we support one primary language only.

**Comment by tohaitrieu** [comment]
Your item you've requested is not currently available in the Vietnammese store

**Comment by vbresults** [comment]
@tohaitrieu When I visit the link, it is showing in the app store;
