### ISSUE TITLE
Xenforo add-on details?

### ISSUE THREAD

**Issue by 8BiTw0LF** [turnkeymobileapps/help-center#25]
Some details are missing from the add-on - can you please support me in this matter. There are no push-notifications in the apps for Android and iOS.
![screenshot 1 png 1](https://cloud.githubusercontent.com/assets/20681312/22015032/aa1aadd2-dca0-11e6-9ed9-77a5f493d0c3.png)

Also my Google Play App ID is still pending at: https://www.turnkeymobileapps.com/app_profiles/view/110

**Comment by vbresults** [comment]
The app id still pending was a manual error, apologies for that;

**Comment by 8BiTw0LF** [comment]
No problem - I'm just glad you can help :)

I've just updated the add-on and it now says 2.0? I followed the UPGRADE.txt

**Comment by vbresults** [comment]
Ok, if you followed the UPGRADE.txt, you will just need to force close the app and open it again, then log in, and you should start receiving alerts (:

**Comment by 8BiTw0LF** [comment]
Still no configuration. And the app says:
![smmmecu](https://cloud.githubusercontent.com/assets/20681312/22016571/0c12d860-dca7-11e6-8536-d9ee9dd445fc.png)

**Comment by vbresults** [comment]
- If you follow the instructions in UPGRADE.txt, the 3 settings you referred to in your initial post will no longer be there.
- The notification settings prompt is not a bug, that is coming in another version that hasn't been released yet
