### ISSUE TITLE
About android app

### ISSUE THREAD

**Issue by fitnessbiim** [turnkeymobileapps/help-center#26]
Hello, my app was shared in the app store store. thank you. When will Google play store store be shared?

Android
Status: Waiting For Review
App ID: Pending
Est. Status Update

Dec 27th
iOS
Status: Ready For Sale
App ID: 1188672426

**Comment by vbresults** [comment]
We have sent you multiple emails about this, you didn't upload the APP_PUB_AUTH.txt file that came with your add-on:

**Comment by fitnessbiim** [comment]
Uploaded. complete
https://www.fitnessbilim.com/forum/APP_PUB_AUTH.txt

When the app becomes the play store?

**Comment by vbresults** [comment]
Your file is empty; you need to upload the APP_PUB_AUTH.txt that comes with your add-on (log in and download at www.turnkeymobileapps.com).

**Comment by fitnessbiim** [comment]
Sorry. Go to link please

**Comment by fitnessbiim** [comment]
Uploaded. complete
https://www.fitnessbilim.com/forum/APP_PUB_AUTH.txt

When the app becomes the play store?

**Comment by vbresults** [comment]
Within 72 hours (:

**Comment by fitnessbiim** [comment]
What is the time to publish google play store? I am excited :))
