### ISSUE TITLE
Installing .ipa and .apk degrade during installation

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#3]
Installing .ipa and .apk degrade during installation on Apple iPhone 10.1 and Android Tablet 4.4.2
Can you see my settings that do not appear correctly?
https://www.turnkeymobileapps.com/app_profiles/view/100

**Comment by vbresults** [comment]
Hello,

What do you mean by degrade?

**Comment by vbresults** [comment]
Hello,

What do you mean by degrade?

**Comment by robru123** [comment]
If I install the .apk on the Android tablet.
Comes on the desktop to be an icon.
If you click there, the app starts and closes again immediately.

If I install the .ipa on the iPhone.
Is installed the app.
After the installation is complete the icon disappears from the screen.

**Comment by vbresults** [comment]
Ah, you can only use the IPA if you provided a device UDID when you signed up for the app, if you didn't the app will not install (icon disappears).

If you want to try it on a specific device, send the UDID to help@turnkeymobileapps.com from the email address listed on your account;

Looking into the Android issue

**Comment by robru123** [comment]
Thank you for your help. I sent an email with the information.

**Comment by vbresults** [comment]
@robru123 A new 2.0 IPA has been rebuilt that works with that UDID, and the general IPA has been submitted to the app store; additionally, your Android APK has been rebuilt.

I tested both of these for your specific app on devices and they work successfully; please re-download them and confirm if everything looks good on your end or not (:

**Comment by tommydamic68** [comment]
Lost  my password tommydamic68@yahoo.com

**Comment by robru123** [comment]
@vbresults The new app works fine on an Android tablet, I also noticed that the app is already available in Google Play Store.

The apple rebuild app still does not work on my iPhone. The same problem as with the previous version.

Thank you for your awsome support!

**Comment by vbresults** [comment]
@robru123 If you try to install it on a device that doesn't match the UDID you provided, it will not install -- I set two UDIDs, yours and mine, and it worked -- so maybe this is the wrong device?

@tommydamic68 In the future, please post your issues in a new ticket, as this one is on an entirely different issue.  Your reset has been processed.

**Comment by robru123** [comment]
@vbresults The UDID code I gave via email associated with the iPhone where I do the installation.
I'll just wait until the app is approved by Apple so I can test it on other Apple devices.

![app](https://cloud.githubusercontent.com/assets/24276544/20830304/3604db50-b880-11e6-9cc8-ea0ea05c1594.png)
