### ISSUE TITLE
IOS App

### ISSUE THREAD

**Issue by psx123** [turnkeymobileapps/help-center#31]
On IOS 10.3 the app crashes, my members have been reporting.

**Comment by vbresults** [comment]
@psx123 What is your app id?

**Comment by psx123** [comment]
1174119181

**Comment by vbresults** [comment]
@psx123 When does it crash specifically?

**Comment by psx123** [comment]
When opening

**Comment by vbresults** [comment]
@psx123 What specific version of the app are the people reporting these crashes using?

**Comment by psx123** [comment]
The latest one

**Comment by vbresults** [comment]
@psx123 Having trouble reproducing this -- does this happen for 10.3+ exclusively or also <= 10.2?  If so, what devices?  Sorry for all the questions, just trying to recreate the crash

**Comment by vbresults** [comment]
Due to major changes in upcoming 2.2, closing this for now.  If the issue is still there, please re-open this ticket.
