### ISSUE TITLE
Disabled apps to be re-enabled today?

### ISSUE THREAD

**Issue by aminsabet** [turnkeymobileapps/help-center#32]
Are the free apps that were disabled pending update to remove Minimal UI on track to be re-enabled today?  If not, can you please advise as to ETA so we can advise our members?

**Comment by aminsabet** [comment]
I just saw your response in the Xenforo thread: https://xenforo.com/community/threads/free-mobile-apps-for-xenforo-with-addon-theme-support-android-iphone.119852/page-6#post-1130163

Thank you.

**Comment by aminsabet** [comment]
One of my apps seems to still be disabled: FujiXspot User Group.  Can you please take a look and re-enable it?  Thanks, Amin

**Comment by vbresults** [comment]
@aminsabet Re-enabled, apologies for missing this.
