### ISSUE TITLE
App is running very slow

### ISSUE THREAD

**Issue by 8BiTw0LF** [turnkeymobileapps/help-center#34]
Hi :) After installing 2.1.2 on my forum, the apps are running very slow and can't be used anymore.

Will you please take a look?

http://vikingsofdestiny.dk/

**Comment by vbresults** [comment]
Hello,

What part of the app is slow, and is this occurring on Android, iOS, or both?

**Comment by 8BiTw0LF** [comment]
It is "lagging" heavily on all forum boards. When scrolling the forums, chat, etc. becomes invisible. 
Only on Android - everything is fine on iOS.

**Comment by vbresults** [comment]
This is fixed in the 2.2 release; if you experience any issues when it comes out, please let us know (:
