### ISSUE TITLE
Policy rejected 

### ISSUE THREAD

**Issue by matt-derrick** [turnkeymobileapps/help-center#38]
After waiting TWO MONTHS for my app to be submitted, I finally get an email today with the ever-so-helpful message "your app status is policy rejected". 

I log into my turnkey account and all it says is "policy rejected" in red. What the hell does that even mean? Why can't you just tell us what's wrong without sending bizarre and cryptic emails?

**Comment by BushcraftUSA** [comment]
I received the same thing after waiting as well.  

I would be interested in knowing why my family friendly, no politics or religious discussion allowed, forum was rejected.

**Comment by vbresults** [comment]
> The new restrictions are too prohibitive for most forums who would need a free app. We are temporarily halting new applications for using it while we work on relaunching it later in the year after a complete restructuring.

Existing published free apps are unaffected and remain functional unless otherwise stated, and pending requests for free apps have been rejected. When there are more details, we'll send them to applicants at the provided email addresses.

When ready, we'll repost the details here and request this resource to be restored. There are no further details at this time.

**Comment by BushcraftUSA** [comment]
I was planning on paying for mine and only had the free app for evaluation.

Are you saying that paying for it, we will be able override the policy rejection by Apple and Google? If so, let me know how to proceed to make that happen.

**Comment by vbresults** [comment]
@BushcraftUSA Your demo of the paid version was policy rejected in error, it has been restored.

**Comment by vbresults** [comment]
@BushcraftUSA I thought your app was rejected in error but it looks like you were on the free plan, not the demo of the paid plan (separate) -- either way, you can upgrade by clicking the blue button.

**Comment by vbresults** [comment]
@BushcraftUSA Edit: thought your app was rejected in error but it looks like you were on the free plan, not the demo of the paid plan (separate) -- either way, you can upgrade by clicking the blue button.

A policy rejection is a rejection by us, not the app stores.  Your app has been unrejected.
