### ISSUE TITLE
Change pictures in iTunes en Google Play store

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#39]
How can I change (renew) the pictures in the iTunes and Google Play store?

Thank you :)

**Comment by turnkeymobileapps** [comment]
Only possible with Enterprise plan.  With it, you own the app store account and can change the screenshots at any time.  With Turnkey or FMA you are using our account so it's not possible.

**Comment by robru123** [comment]
Thank you for your support.
