### ISSUE TITLE
Error: Zend_Feed_Exception: Invalid parameter

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#4]
System: Xenforo 1.5.11

**Error Info:**
`Zend_Feed_Exception: Invalid parameter: parameter must be a non-empty string - library/Zend/Feed/Writer/Entry.php:202`
**Stack Trace:**
`#0 /var/www/html/library/MobileInterface/ViewPublic/Forum/GlobalRss.php(57): Zend_Feed_Writer_Entry->setContent('')
#1 /var/www/html/library/MobileInterface/ViewPublic/Forum/GlobalRss.php(41): MobileInterface_ViewPublic_Forum_GlobalRss->_importAlertsToFeed(Object(Zend_Feed_Writer_Feed), Array)
#2 /var/www/html/library/XenForo/ViewRenderer/Abstract.php(227): MobileInterface_ViewPublic_Forum_GlobalRss->renderRss()
#3 /var/www/html/library/XenForo/ViewRenderer/Rss.php(31): XenForo_ViewRenderer_Abstract->renderViewObject('MobileInterface...', 'Rss', Array, '')
#4 /var/www/html/library/XenForo/FrontController.php(606): XenForo_ViewRenderer_Rss->renderView('XenForo_ViewPub...', Array, '', NULL)
#5 /var/www/html/library/XenForo/FrontController.php(158): XenForo_FrontController->renderView(Object(XenForo_ControllerResponse_View), Object(XenForo_ViewRenderer_Rss), Array)
#6 /var/www/html/index.php(13): XenForo_FrontController->run()
#7 {main}`
**Request State:**
`array(3) {
  ["url"] => string(70) "https://www.caviaforum.nl/forums/-/index.rss?mobile_interface.alerts=1"
  ["_GET"] => array(1) {
    ["mobile_interface_alerts"] => string(1) "1"
  }
  ["_POST"] => array(0) {
  }
}`

**Comment by vbresults** [comment]
This is fixed, please re-download the add-on and overwrite the existing files (:

**Comment by robru123** [comment]
This error I have not seen again in the ACP.

**Comment by vbresults** [comment]
Re-opening this because someone else reported the issue after we applied a fix -- if they don't see it again after re-downloading the new add-on zip and overwriting the old files, this will be closed again.

**Comment by robru123** [comment]
Understood
Thank you :)

**Comment by vbresults** [comment]
No more reports, consider this fixed (:
