### ISSUE TITLE
Some apps still waiting for update?

### ISSUE THREAD

**Issue by aminsabet** [turnkeymobileapps/help-center#40]
I saw that some of my apps had been updated in the Apple App Store, so I updated the XenForo plugin on all my sites.  

Now some of the apps no longer function and say "Your app is out of date.  Please upgrade to the latest version on the app store/market".

Is it just a matter of waiting for those upgraded versions to make it to the app store?

**Comment by turnkeymobileapps** [comment]
Correct, more details will be in the upcoming announcement (:
