### ISSUE TITLE
add-on out of date (2.1.x add-on with 2.2x+ app)

### ISSUE THREAD

**Issue by BushcraftUSA** [turnkeymobileapps/help-center#41]
Myself and my members are having problems with the app that just went live on Google Play (iOS not approved yet).  Keep in mind that I am a super-admin and having the same issue as the other members. All of these are present after a member logs in.

1. Trying to access the Settings results in a message to login
2. Trying to use the camera results in a message to login
3. Trying to use the Edit "pencil" in the lower-right does nothing on forum/thread/post views. This needs to go away. It is redundant if it actually worked.
4. The 3 lines in the upper-right does nothing
5. Loads much slower than the "free" demo
6. Camera was in the top bar in the "free" demo. It needs to go back there, where there is room, instead of floating over readable space at the bottom where it covers up part of the forum/thread/post view.

**Comment by vbresults** [comment]
Hello,

All of these issues are symptoms of the add-on being out of date; what version does the add-on shows in the admin panel?

**Comment by turnkeymobileapps** [comment]
Hello,

Most of these issues are symptoms of the add-on being out of date.  An announcement is going out shortly about the update; we had to get the apps on the app store first for technical reasons.

This is not related to "free" vs "paid", as both apps are identical, rather this is the updated 2.2 version but due to the add-on being out of sync, most of it is not working.

Apologies for the inconvenience and we'll provide more details soon.  By the way, as TMA client now, you are entitled to email support at help@turnkeymobileapps.com

**Comment by BushcraftUSA** [comment]
message and likes_summary were messed up and giving errors, with the Twenty Two file that had to be imported.

-I copied message from my default to your Twenty Two and the merge/out of date error went away.
-likes_summary: I also copied from my default. There is no "thumbs_up" in Xenforo. It is called "like."

In addition, Xenforo does not allow an on-server link for installation of style sheets, so your instructions are wrong. I had to use the copy on my hard drive to install the style sheet, Twenty Two.

And please fix whatever is in your style sheet, Twenty Two, that has killed my PC-based users from selecting my other style sheets. Selecting style sheets on PC's is not even an option anymore and I don't use the default Blue on my board.

**Comment by vbresults** [comment]
@BushcraftUSA The general way the style sheet works is that you only select the "app style" checkbox for styles you want in-app, every other style is left unchecked.

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA The general way the style sheet works is that you only select the "app style" checkbox for styles you want in-app, every other style is left unchecked.

**Comment by BushcraftUSA** [comment]
I am fully aware of that and it has been completed, and works fine in the app.

The problem is that when I installed your Twenty Two style sheet, it removed the ability of PC-based users to select any style sheets. The one that is present is not our default, but your blue style sheet, Twenty Two. Something is wrong with that style sheet or your server-side application. I need that fixed ASAP. We are an outdoor site and do not use the blue style sheet.

Guy

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA The way to allow your style sheets to be selected by a PC is to create a child style of your original, then mark that one as the app style, not the parent style -- does this work for you?

**Comment by BushcraftUSA** [comment]
I guess I missed that in the instructions. That was not necessary during the demo.

I will create 4 new style sheets and see if that works then.

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA Correct; this wasn't necessary during the demo because the demo was running on our previous version of TMA (2.1.x) -- 2.2 is a major upgrade although the change from .1 to .2 wouldn't indicate that.  Apologies for the trouble this has caused you

**Comment by turnkeymobileapps** [comment]
Split into 3 tickets for different issues (:

**Comment by BushcraftUSA** [comment]
I created all new child style sheets and now I have the following issue:

-The style sheets came back to PC-based selection options; however, all of the child style sheets show up also, doubling my selection options on a PC.
-All of the selection options have disappeared on the Turnkey app, leaving only the default. This is the same whether Twenty Two is a child or parent level style sheet.

Question: What are the back/dbl back/forward/dbl forward, for? When I use them the app crashes.

Question: can you move the camera somewhere else and remove the edit? They cover up the bottom of the screen and the edit is redundant for the Xenforo capabilities. Style sheet selection is hidden behind the camera icon.

**Comment by vbresults** [comment]
@BushcraftUSA Please create a new ticket for this new set of questions

**Comment by BushcraftUSA** [comment]
Will do. The remaining issues are related to the original ticket.

**Comment by vbresults** [comment]
@BushcraftUSA The first set of issues was largely due to the add-on being out of date, these are post-2.2 questions

**Comment by vbresults** [comment]
@BushcraftUSA Please create a new ticket for the selection issue
