### ISSUE TITLE
Out of date app

### ISSUE THREAD

**Issue by wonko123** [turnkeymobileapps/help-center#42]
Received email saying you had released a new update so installed as per upgrade instructions and now when the app is opened we get:-

> Your app is out of date.Please upgrade to the latest version on the app store/market.

**Comment by turnkeymobileapps** [comment]
@wonko123 We are just waiting for apple to approve your app, sorry for the delay

**Comment by wonko123** [comment]
Cool no worries, thanks for your work on this app 👍

**Comment by Dannymh** [comment]
I have started getting this error after updating the addon today
