### ISSUE TITLE
Can't select style sheet out of app

### ISSUE THREAD

**Issue by turnkeymobileapps** [turnkeymobileapps/help-center#43]
Split from #41

> The general way the style sheet system works in 2.2 is that you only select the "app style" checkbox for styles you want in-app, every other style is left unchecked.
> 
> The way to allow your style sheets to be selected by a PC is to create a child style of your original, then mark that one as the app style, not the parent style.

**Comment by turnkeymobileapps** [comment]
The general way the style sheet system works in 2.2 is that you only select the "app style" checkbox for styles you want in-app, every other style is left unchecked.

The way to allow your style sheets to be selected by a PC is to create a child style of your original, then mark that one as the app style, not the parent style.

**Comment by turnkeymobileapps** [comment]
> @BushcraftUSA says: I guess I missed that in the instructions. That was not necessary during the demo.
> 
> I will create 4 new style sheets and see if that works then.

**Comment by BushcraftUSA** [comment]
I am not sure why this was closed and what happened to my response.

PC-based style sheets are now available, although there are twice as many with the child style sheets. That is unacceptable and takes resources.

App-based style sheets are now no-longer available. This needs to be fixed.

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA This ticket was closed prior to the note about double styles, it has been consolidated now

**Comment by BushcraftUSA** [comment]
I still have the double listing of style sheets on a PC, but I have fixed the non-selection problem with the app, with the same double listing result.

I created a child of your Twenty Two style sheet, disabled the parent version for selectability by members, and then the selection option worked in the app, except that now there are the double amounts there too.

I reckon something needs to be worked out where the PC version doesn't show up in the app. If members select a non-app version of a style sheet, then the upper-right menu will not work and the header will show up, since the extra.css info is not present in the parent versions.

**Comment by turnkeymobileapps** [comment]
> I reckon something needs to be worked out where the PC version doesn't show up in the app. If members select a non-app version of a style sheet, then the upper-right menu will not work and the header will show up, since the extra.css info is not present in the parent versions.

This was the intended functionality but it appears to not be working that way, we are fixing it right now

**Comment by BushcraftUSA** [comment]
Thank you.

**Comment by BushcraftUSA** [comment]
Style sheet selection has disappeared in the app again.

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA Would this happen to be occurring consistently as a guest but not a member?

**Comment by BushcraftUSA** [comment]
I couldn't tell you since you guys didn't include a log-out feature in the menu.

**Comment by vbresults** [comment]
The missing items related to #47

**Comment by turnkeymobileapps** [comment]
The missing items are caused by #47 not this
