### ISSUE TITLE
Template errors

### ISSUE THREAD

**Issue by turnkeymobileapps** [turnkeymobileapps/help-center#44]
Split from #41

> @BushcraftUSA says: message and likes_summary were messed up and giving errors, with the Twenty Two file that had to be imported.

> -I copied message from my default to your Twenty Two and the merge/out of date error went away.

> -likes_summary: I also copied from my default. There is no "thumbs_up" in Xenforo. It is called "like."

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA What version of XenForo is running?

**Comment by BushcraftUSA** [comment]
Version 1.5.8

**Comment by turnkeymobileapps** [comment]
When you say the message style was messed up, what do you mean?

**Comment by BushcraftUSA** [comment]
There was an error that the version of Message in Twenty Two, was older than current version (of Xenforo?). It gave an option to merge, which I selected, but it said it was incompatible. I copied the contents of Message from my default style sheet, to Twenty Two's version, and the incompatibility message went away.

**Comment by turnkeymobileapps** [comment]
The next update will be re-based with 1.5.8 templates.
