### ISSUE TITLE
What are the header arrows supposed to do?

### ISSUE THREAD

**Issue by BushcraftUSA** [turnkeymobileapps/help-center#45]
What are the back/dbl back/forward/dbl forward, for? When I use them the app crashes.

**Comment by turnkeymobileapps** [comment]
They are supposed to navigate your app forward and backwards one page (the double arrows go to first/last page) -- I'm downloading your app now to see the issue

**Comment by vbresults** [comment]
@BushcraftUSA Would this crashing happen to be Android?

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA Would this crashing happen to be Android?

**Comment by BushcraftUSA** [comment]
Yes. 

The iOS version has not been approved yet.

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA I can't reproduce this problem -- what version of android and what device?

**Comment by BushcraftUSA** [comment]
I am using a Note 4 and I am not sure what version. It just tried to load an update while I was working on this/these issues and I did not let it load.

**Comment by vbresults** [comment]
@BushcraftUSA An update of TMA or an update of Android?

Please share the Android version using these instructions: http://www.wikihow.com/Check-What-Android-Version-You-Have

**Comment by BushcraftUSA** [comment]
Android. Do I need to download a new version of the TMA app?

**Comment by vbresults** [comment]
@BushcraftUSA What is the version of your TMA app?

**Comment by BushcraftUSA** [comment]
2.2.2

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA [Android version](http://www.wikihow.com/Check-What-Android-Version-You-Have)?

**Comment by BushcraftUSA** [comment]
Android version: 6.0.1

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA Ok, performing diagnostics now (:

**Comment by turnkeymobileapps** [comment]
Fixed the bug causing the rewind and forward buttons to function even if you were already viewing the first or last page giving the impression of a "refresh", this fix will be available in the next update.
