### ISSUE TITLE
Please remove Edit and move the Camera

### ISSUE THREAD

**Issue by BushcraftUSA** [turnkeymobileapps/help-center#46]
Can you move the camera somewhere else and remove the edit? They cover up the bottom of the screen and the edit is redundant for the Xenforo capabilities. 

Style sheet selection is hidden behind the camera icon. 

Terms of Use, Privacy Policy and Contact Us links are hidden behind the pencil/edit icon.

**Comment by turnkeymobileapps** [comment]
There is a "Minimal UI" style property in TMA that hides these two buttons, we just need to update the app store apps to 2.2.3 since without it the styleprop does nothing.

The update will be released in a few weeks from now
