### ISSUE TITLE
Formatting Overrides by App

### ISSUE THREAD

**Issue by BushcraftUSA** [turnkeymobileapps/help-center#47]
I am beyond irritated with this. Why are my style properties overwritten????

As you can see in the attached screenshot:

1. the background is white. That is Twenty Two's default, not mine style sheets. We use earthtones.
2. What is up with those circles???? As you can see, letters are moving to the next line and throwing the whole formatting off.

![screenshot_2017-04-16-04-20-48](https://cloud.githubusercontent.com/assets/26242772/25069953/7b6a71fe-225d-11e7-9c7a-f29f170795cb.png)

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA This is a bug and the mish-mashing I was talking about.  Never seen this before but we are working on a fix right now.

**Comment by turnkeymobileapps** [comment]
Fixed in [v2.2.3 of the add-on](https://xenforo.com/community/resources/turnkey-mobile-apps-for-xenforo-with-addon-theme-support-android-iphone.4731/updates).
