### ISSUE TITLE
Add-on Corruption

### ISSUE THREAD

**Issue by BushcraftUSA** [turnkeymobileapps/help-center#48]
I tried to logout of the app, but that seems to be missing from the drop-down menu in the upper-right.

Also missing is an option to view and edit your profile.

Those are pretty important features to be excluded.

**Comment by BushcraftUSA** [comment]
Also in the drop-down menu, the first item shows "mobile_interface_tab," which when clicked on, goes to a random thread shown below. Please note the three odd header links.

![screenshot_2017-04-16-04-56-35](https://cloud.githubusercontent.com/assets/26242772/25070058/458fb9dc-2261-11e7-9a21-75a556ba6076.png)

**Comment by BushcraftUSA** [comment]
I originally started looking around the drop-down menu because I was trying to change my style sheet after selecting a non-app version (parent of an app version). Now, I cannot select a different style sheet and was trying to get to my profile preferences...but alas, you guys didn't include that basic functionality in the app.

**Comment by vbresults** [comment]
@BushcraftUSA Many of the things you are reporting are not being seen on other forums, would you mind allowing us to perform the add-on upgrade to confirm this isn't an upgrade issue?

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA Many of the things you are reporting are not being seen on other forums, would you mind allowing us to perform the add-on upgrade to confirm this isn't an upgrade issue?

**Comment by BushcraftUSA** [comment]
That will be fine. What do you need?

**Comment by turnkeymobileapps** [comment]
@BushcraftUSA Please send a create one-time fully privileged xenforo admin login and (either ssh or ftp) details with write access to help@turnkeymobileapps.com
