### ISSUE TITLE
Slow loading Twenty Two skin (2.2.2)

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#49]
Slow loading Twenty Two skin (2.2.2), when option enabled.

![afbeelding](https://cloud.githubusercontent.com/assets/24276544/25072365/8529371a-22cc-11e7-9ea1-1ba904c823a3.png)

**Comment by turnkeymobileapps** [comment]
@robru123 We added a new setting called "Shield Loading Pages" so it feels faster for you: https://xenforo.com/community/resources/turnkey-mobile-apps-for-xenforo-with-addon-theme-support-android-iphone.4731/updates (:

**Comment by robru123** [comment]
Thank you for your support 👍
