### ISSUE TITLE
ErrorException: Fatal Error: Allowed memory size of X bytes exhausted

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#5]
**Error Info:**
`ErrorException: Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) - library/XenForo/Helper/Php.php:206`
**Stack Trace:**
`#0 [internal function]: XenForo_Application::handleFatalError()
#1 {main}`
**Request State:**
`array(3) {
  ["url"] => string(72) "https://www.caviaforum.nl/forums/-/index.rss?mobile_interface.watching=1"
  ["_GET"] => array(1) {
    ["mobile_interface_watching"] => string(1) "1"
  }
  ["_POST"] => array(0) {
  }
}`

**Comment by vbresults** [comment]
This has just been patched; please re-download and overwrite the add-on files via FTP

**Comment by robru123** [comment]
I now just overwrite only the files, and no upgrade done with the XML file.
The error is still present.

![error](https://cloud.githubusercontent.com/assets/24276544/20860137/5463489c-b971-11e6-878d-4738dc0a70e5.png)

**Comment by vbresults** [comment]
Looking into this; we can't produce this issue on our test board so it is taking a bit of time to resolve.  If you can email an admin login and FTP login to help@turnkeymobileapps.com, it will help so we can fix this faster, but it is not required.

**Comment by robru123** [comment]
Currently I have no errors.
If the errors appear again I will be an admin account for you.

**Comment by vbresults** [comment]
No more reports, consider this fixed (:
