### ISSUE TITLE
Read timed out after 10 seconds (2.2.2)

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#50]
`Zend_Http_Client_Adapter_Exception: Read timed out after 10 seconds - library/Zend/Http/Client/Adapter/Socket.php:514`

`#0 /var/www/html/community/library/Zend/Http/Client/Adapter/Socket.php(330): Zend_Http_Client_Adapter_Socket->_checkSocketReadTimeout()
#1 /var/www/html/community/library/Zend/Http/Client.php(989): Zend_Http_Client_Adapter_Socket->read()
#2 /var/www/html/community/library/MobileInterface/PushAlert/Transport.php(99): Zend_Http_Client->request('POST')
#3 /var/www/html/community/library/MobileInterface/PushAlert/Transport.php(78): MobileInterface_PushAlert_Transport::send('messages', Array)
#4 /var/www/html/community/library/MobileInterface/PushAlert/Transport.php(138): MobileInterface_PushAlert_Transport::messages(Array)
#5 /var/www/html/community/library/XenForo/Model/Cron.php(356): MobileInterface_PushAlert_Transport::send_batch_queue(Array)
#6 /var/www/html/community/library/XenForo/Deferred/Cron.php(24): XenForo_Model_Cron->runEntry(Array)
#7 /var/www/html/community/library/XenForo/Model/Deferred.php(295): XenForo_Deferred_Cron->execute(Array, Array, 8, '')
#8 /var/www/html/community/library/XenForo/Model/Deferred.php(429): XenForo_Model_Deferred->runDeferred(Array, 8, '', false)
#9 /var/www/html/community/library/XenForo/Model/Deferred.php(374): XenForo_Model_Deferred->_runInternal(Array, 8, '', false)
#10 /var/www/html/community/deferred.php(23): XenForo_Model_Deferred->run(false)
#11 {main}`

**Comment by turnkeymobileapps** [comment]
This is a typical error and can be safely ignored; if the server log option is off for TMA and the add-on is up to date you shouldn't see these (:

**Comment by robru123** [comment]
Thank you :)
