### ISSUE TITLE
Unable to post

### ISSUE THREAD

**Issue by wonko123** [turnkeymobileapps/help-center#52]
Hi, my members are having trouble posting on android, I have a link to their post with screenshots:- https://www.pc-sg.uk/threads/pc-sg-app.3490/page-3#post-24606

**Comment by turnkeymobileapps** [comment]
@wonko123 This was fixed in the update a few days ago, but to apply the fix for this specific issue, the style must be overwritten with the new version using the style-twenty-two.xml
