### ISSUE TITLE
ErrorException: Argument 1 passed to XenForo_Model_Post::canLikePost() must be of the type array, boolean given: -> Fixed (read internally)

### ISSUE THREAD

**Issue by Dannymh** [turnkeymobileapps/help-center#53]
When entering some forums users are getting the following error. 

```
ErrorException: Argument 1 passed to XenForo_Model_Post::canLikePost() must be of the type array, boolean given, called in /var/www/silvertails.net/library/MobileInterface/ViewPublic/Forum/View.php on line 76 and defined - library/XenForo/Model/Post.php:822
Generated By: Lyonstomenzies, 22 minutes ago
Stack Trace
#0 /library/XenForo/Model/Post.php(822): XenForo_Application::handlePhpError(4096, 'Argument 1 pass...', '/var/www/silver...', 822, Array)
#1 /library/MobileInterface/ViewPublic/Forum/View.php(76): XenForo_Model_Post->canLikePost(false, Array, Array)
#2 /library/MobileInterface/ViewPublic/Forum/View.php(42): MobileInterface_ViewPublic_Forum_View->_commit(Array)
#3 /library/XenForo/ViewRenderer/Abstract.php(227): MobileInterface_ViewPublic_Forum_View->renderHtml()
#4 /library/XenForo/ViewRenderer/HtmlPublic.php(71): XenForo_ViewRenderer_Abstract->renderViewObject('XenForo_ViewPub...', 'Html', Array, 'forum_view')
#5 /library/XenForo/FrontController.php(607): XenForo_ViewRenderer_HtmlPublic->renderView('XenForo_ViewPub...', Array, 'forum_view', NULL)
#6 /library/XenForo/FrontController.php(158): XenForo_FrontController->renderView(Object(XenForo_ControllerResponse_View), Object(XenForo_ViewRenderer_HtmlPublic), Array)
#7 /index.php(13): XenForo_FrontController->run()
#8 {main}

```
This is fixed by making sure that we parse the the firstPost variable as an array. This is only a temp fix, ideally we should not be calling this when we enter a forum, only when we enter a post so I will have to look to see if I can patch this upline, however the following is a quick patch

in /library/mobileinterface/ViewPublic/Forum/View.php on line 75 add

```
 if(!is_array($firstPost))	{
 			$firstPost = array($firstPost);
 }
```

all it does is for $firstPost to an array instead of a boolean

**Comment by Dannymh** [comment]
FYI this will cause another silent error of undefined index, which is why I need to see why this code gets called on forum view

**Comment by turnkeymobileapps** [comment]
This was fixed 10 days ago but as the next update hasn't been finished yet on the app side, it wasn't announced.  The add-on is already updated though, so if you download it now, it will be fixed immediately (:

**Comment by Dannymh** [comment]
Awesome thank you. I should be grabbing the updates instead of trying to code it myself :)

I just came up with a better fix too haha
