### ISSUE TITLE
Missing apple-touch-icon.png in package

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#6]
I see that my CDN servers provide a 404 code in the absence of the image: apple-touch-icon.png
/js/mobile_interface/libraries/smart-app-banner/apple-touch-icon.png
Is there a reason for that?

**Comment by vbresults** [comment]
This was due to a bug, it has just been fixed -- thank you for reporting it (:

To get the icon, you can re-download the zip and overwrite the files, or just copy that specific file from the zip, but there's no need to import the add-on XML for this specific issue.

**Comment by robru123** [comment]
Fixed!

Thank you ;)

**Comment by robru123** [comment]
Question about this fix.
I think the correct location of the image (apple-touch-icon.png) must be:

/ js / mobile_interface / libraries / smart-app-banner /
Insteed of:
 / js / mobile_interface / smart-app-banner /

Can you confirm this?

**Comment by vbresults** [comment]
@robru123 Correct!  Thanks again for reporting this, it has been updated in the add-on and can be applied by re-download/overwrite (:

**Comment by robru123** [comment]
Thank you :)
