### ISSUE TITLE
How to changing forum path Xenforo in Apps

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#7]
Because of my new project I've moved all the data from the root to a folder.
How do I apply this new path in the Android and Apple App?

Thank you.

**Comment by vbresults** [comment]
Temporarily do a 301 redirect so that the old location goes to the new one; if your board url setting is changed, there is nothing else to do -- the add-on automatically sets the new path after a few hours.

**Comment by robru123** [comment]
Done, thank you :)
