### ISSUE TITLE
Error: Call to a member function getBody() on boolean

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#8]
**Error Info:**
Error: Call to a member function getBody() on boolean - library/MobileInterface/PushAlert/Transport.php:18

**Stack Trace:**
#0 /var/www/html/community/library/MobileInterface/ControllerPublic/Account.php(5): MobileInterface_PushAlert_Transport::register(Object(EWRcarta_ControllerPublic_Account))
#1 /var/www/html/community/library/XenForo/FrontController.php(351): MobileInterface_ControllerPublic_Account->actionPushAlertRegister()
#2 /var/www/html/community/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#3 /var/www/html/community/index.php(13): XenForo_FrontController->run()
#4 {main}

**Request State:**
array(3) {
  ["url"] => string(63) "https://www.caviaforum.nl/community/account/push-alert-register"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(4) {
    ["platform"] => string(7) "android"
    ["token"] => string(152) "db0r2y-4QvU:APA91bG6NMJcDHmI_9bShSOBRNDQJnHMt9bCLG5PeGT3Vs-jXVxJrqXh3HSwS6R03aCKxAAcFOArlwrZ-zoMxdVI7Utdy-cOzSRMoTGsfYvbWyIxxJskH6zEF1_ZeVCDDzV7FLOwoMxL"
    ["_xfResponseType"] => string(4) "json"
    ["_xfToken"] => string(8) "********"
  }
}

**Comment by vbresults** [comment]
Thank you for reporting, please re-download the add-on and overwrite the existing files (:

**Comment by robru123** [comment]
Thank you :)
