### ISSUE TITLE
XenForo Add-on Upgrade Instructions to version 2.1.1

### ISSUE THREAD

**Issue by robru123** [turnkeymobileapps/help-center#9]
1. Download the zip, then unzip the *contents* of the upload folder to your XenForo directory
Done!
1b. If performing a major upgrade, uninstall the add-on
Done!
2. Go to `Admin > Install New Add-on > Install from file on server
Done!
3. Log In at https://www.turnkeymobileapps.com
Done!
4. Visit your app's page, and tick the "I Confirm the Add-on Is Installed and Active" box
Not available, There is no "I Confirm the Add-on Is Installed and Active" box present !!

![confirmbox](https://cloud.githubusercontent.com/assets/24276544/21388317/025b4a5e-c77c-11e6-90b9-2ba1d430f82a.png)

Regard
Ronald

**Comment by vbresults** [comment]
This step wasn't supposed to be in the upgrade instructions, it's only for installs; thank you for reporting this, it's been updated in the add-on generator (:
